const path = require("path")
const os = require("os")
const fs = require("fs")

console.log("os constants")
console.log()
console.log(`eol: ${os.eol}`)
console.log(`arch: ${os.arch}`)
console.log(`platform: ${os.platform}`)
console.log(`null: ${os.null}`)
console.log(`endianness: ${os.endianness}`)
console.log(`isPosix: ${os.isPosix}`)
console.log(`type: ${os.type}`)
console.log()
console.log("path constants")
console.log()
console.log(`sep: ${os.sep}`)
console.log(`delimiter: ${os.delimiter}`)
console.log()
console.log("os grabbers")
console.log()
console.log(`memtotal: ${os.memtotal()}`)
console.log(`memfree: ${os.memfree()}`)
console.log(`memused: ${os.memused()}`)
console.log(`hostname: ${os.hostname()}`)
console.log(`homedir: ${os.homedir()}`)
